config/routes.rb
BlogNagamemo::Application.routes.draw do
  resources :materials do
    member do
      get :now
    end
  end

  resources :histories do
    member do
      get :materials
    end
  end

  resources :offline_download_records do
    member do
      get :log
      get :status
      get :download
    end
  end

	resources :users do
		resources :comments
    resources :offline_download_records
		resources :posts do
			resources :comments
		end
	end

	resources :posts do
		resources :comments
	end

	resources :comments
  resources :file_records
	resources :sessions

	root 'posts#index'
	match 'about', to: 'static_page#about', via: 'get'
	match 'sign_up', to: 'users#new', via: 'get'
	match 'edit_me', to: 'users#edit_current_user', via: 'get'
	match 'show_me', to: 'users#show_current_user', via: 'get'
	match 'sign_in', to: 'sessions#new', via: 'get'
	match 'sign_out', to: 'sessions#destroy', via: 'delete'
	match 'quick_new_post' ,to:'posts#quick_new', via: 'post'
  match 'search', to: 'posts#search', via: 'get'
  match 'set_portrait', to:'users#set_portrait_img', via: 'post'
  match 'lunar_date', to: 'static_page#lunar_date', via: 'get'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include ApplicationHelper
  include SessionsHelper
  validates :user_id, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :file_records, dependent: :destroy
  has_many :viewer_logs, dependent: :destroy

  default_scope { order('id desc') }

  def fetch_last_view options
    return nil if self.id.nil?

    v_type = ViewerLog::VIEW_TYPE_POST
    u = 
      if options.has_key? :user_id
        options[:user_id] 
      elsif options.has_key? :user_ip
        options[:user_ip] 
      end
    options.merge! view_type: ViewerLog::VIEW_TYPE_POST

    key = "/post/#{self.id}/viewer_log/#{v_type}/#{u}"

    last_view = Rails.cache.read key
    if last_view.nil?
      last_view = ViewerLog.where(options).try(:last).try(:created_at)
      Rails.cache.write key, last_view
    end

    last_view 
  end


  def update_last_view viewer_log
    Thread.start do
      viewer_log.save!
      v_type = ViewerLog::VIEW_TYPE_POST

      key = "/post/#{self.id}/viewer_log/#{v_type}/#{viewer_log.user_id || viewer_log.user_ip}"
      Rails.cache.write key, viewer_log.created_at

      conn = ActiveRecord::Base.connection
      conn.close if conn.try :active?
    end
  end
end

app/controllers/posts_controller.rb
#encoding: utf-8
class PostsController < ApplicationController
  include ApplicationHelper
  include ActionView::Helpers::TextHelper

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  after_action :save_file, only: [:create, :update]
  before_action :add_index_page_view_count, only: [:index]
  before_action :add_post_view_count, only: [:show]
  cattr_reader :per_page, :comment_per_page

  @@per_page = 5
  @@comment_per_page = 10
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user, :file_records).paginate(page: params[:page], per_page: @@per_page)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @page = params[:page] || "1"
    @comments = Comment.includes(:user).where(post_id: @post.id).paginate(page: @page, per_page: @comment_per_page)
  end

  # GET /posts/new
  def new
    if signed_in?
      @post = Post.new
    else
      redirect_to sign_in_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  def quick_new
    @post = Post.new(title: MDT.date + '随笔' , content: simple_format(params[:content]) , user_id: current_user.id )
    @post.save 

    @page = params[:page] || "1"
    @comments = Comment.includes(:user).where(post_id: @post.id).paginate(page: @page, per_page: @@comment_per_page)

    redirect_to @post
    #     render 'show'
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    upload_failed_msg = @failed_files.blank? ? "" : "But upload #{pluralize(@failed_files.count, "file")} failed."
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.#{upload_failed_msg}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def search
    @keywords = params[:search_keywords].split

    posts_list = {} and posts_list.default = 0
    all_posts = []

    @keywords.each do |keyword|
      k = "%#{keyword}%"
      posts = Post.includes(:user).where("title like ? or content like ?", k, k)
      posts.each do |post|
        posts_list[post] += 1
      end
    end

    posts_array = (posts_list.sort_by {|key, value| value }).reverse

    posts_array.each do |post, count| 
      all_posts << post ; logger.info post; logger.info count
    end
    logger.info posts_list

    #     @posts = paginate_posts all_posts, page
    @posts = all_posts

    @msg = 
      if @posts.count == 0
        "没有符合条件的日志！"
      else
        "找到#{@posts.count}条记录"
      end

    render 'index'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.includes(:user).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:user_id, :title, :content)
  end

  def save_file
    uploaded_files = params[:files] || []
    @failed_files = []

    uploaded_files.each do |uploaded_file|
      file_name = "#{Date.today.to_s}_#{uploaded_file.original_filename}"
      file_path = "#{Rails.root}/../../shared/files/#{file_name}"

      begin
        FileRecord.create(file_name: file_name, user_id: current_user.id, post_id: @post.id)
        File.open(file_path, 'wb') do |file|
          file.write(uploaded_file.read)
        end
      rescue Exception
        @failed_files << uploaded_file.original_filename
      end
    end
  end

  def add_index_page_view_count
    last_view = 
      if signed_in?
        ViewerLog.fetch_last_view user_id: current_user.id, view_type: ViewerLog::VIEW_TYPE_INDEX
      else
        ViewerLog.fetch_last_view user_ip: request.remote_ip, view_type: ViewerLog::VIEW_TYPE_INDEX
      end

    if last_view.nil? || Time.now - last_view >= 120
      viewer_log = ViewerLog.new
      viewer_log.view_type = ViewerLog::VIEW_TYPE_INDEX
      viewer_log.user_ip = request.remote_ip

      if signed_in?
        viewer_log.login_type = ViewerLog::LOGIN_TYPE_SIGNED_IN
        viewer_log.user_id = current_user.id
      else
        viewer_log.login_type = ViewerLog::LOGIN_TYPE_IP
      end

      ViewCount.increament
      viewer_log.async_save
    end
  end

  def add_post_view_count
    last_view = if signed_in?
                  @post.fetch_last_view user_id: current_user.id
                else
                  @post.fetch_last_view user_ip: request.remote_ip
                end

    if last_view.nil? || Time.now - last_view >= 120
      viewer_log = @post.viewer_logs.build
      viewer_log.view_type = ViewerLog::VIEW_TYPE_POST
      viewer_log.user_ip = request.remote_ip
      if signed_in?
        viewer_log.login_type = ViewerLog::LOGIN_TYPE_SIGNED_IN
        viewer_log.user_id = current_user.id
      else
        viewer_log.login_type = ViewerLog::LOGIN_TYPE_IP
      end


      Post.increment_counter :viewed_times, @post.id 
      @post.update_last_view viewer_log
    end
  end
end

app/helpers/posts_helper.rb
#encoding=utf-8
module PostsHelper
  def is_mine? post
    current_user == post.user
  end

  def print_keywords keywords, count
    search_msg = "在标题和全文中搜索："
    keywords.each { |keyword| search_msg << " #{keyword}" }
    search_msg << "，找到#{count}条日志。"
  end

end

app/views/posts/_form.html.erb
<%= javascript_include_tag "tinymce_config" %>
<%= form_for(@post, html: {multipart: true}) do |f| %>
	<% if @post.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<%#  <%= f.hidden_field nil, :user_id ,current_user +|%>
	<div class="field">
		<%= f.hidden_field :user_id , value: current_user.id %>
	</div>
	<div class="field">
		<%= f.text_field :title, placeholder: "请输入标题" %>
	</div>
	<div class="field">
<%= f.text_area :content, onkeypress: 'ctrlEnter(event, "submit")', placeholder: "请输入正文", rows: 12, class: "tinymce" %>
	</div>
  <div class="field">
    <% unless @post.file_records.blank? %>
      <div id="attachment" class="pull-right">
        <span>附件</span>
        <% @post.file_records.each do |file| %>
          <%= link_to file.file_name, file.url %>
          <%= link_to('删除', file, method: 'delete') %>
          <br />
        <% end %>
      </div>
    <% end %>
    <input type="file" multiple="true" name="files[]" />
  </div>
	<div class="actions">
		<%= f.submit '提交', class: 'btn btn-primary', id: 'submit' %>
    <%= link_to '删除', @post, method: 'delete' %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>编辑帖子</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%#<%= link_to 'Back', posts_path +|%>
<%= link_to_function "返回", "history.go(-1)" %>

app/views/posts/index.html.erb
<%= viewer_msg %>
<%= print_keywords @keywords, @posts.count unless @keywords.blank? || @posts.blank? %>
<% if @posts.count != 0 %>
  <% @posts.each do |post| %>
    <div class="post-overview-item">
      <h2><%= link_to post.title, post %></h2>
      <div>
      <%= image_tag post.user.portrait_url, class: "portrait_s"  %>
      <span class="test"> <%= link_to post.user.name , post.user %> 发表于：<%= post.created_at %> </span>
      </div>
      <br />
      <div class="content">
      <%= simple_format strip_tags(post.content).truncate 400 %>
      </div>
      <br />
      <span class="pull-right">
        <%= "阅览(#{post.viewed_times})评论(#{post.comments.count})" %>
        <%= raw "附件(#{link_to post.file_records.count, "#{post_path(post)}#attachment"})" unless post.file_records.blank?  %>
      </span>
      <%= link_to '全文', post %>
      <% if is_mine?(post) %>
        <%= link_to '修改', edit_post_path(post) %>
        <%= link_to '删除', post, method: :delete, data: { confirm: '确定要删除帖子吗？' } %>
      <% end %>
      <hr />
    </div>
  <% end %>
<% else %>
  <%= @msg || "还没有博客，有时间的话来写一篇吧^_^"  %>
<% end %>
<%= will_paginate(@posts, previous_label: '上一页',next_label: '下一页',:separator=>" | ") if @keywords.nil? %>
<%= button_to '写新博客', new_post_path , method:'get' , class:"btn btn-primary" %>

app/views/posts/new.html.erb
<h1>发新帖</h1>

<%= render 'form' %>

<%= link_to_function "返回", "history.go(-1)" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.title %></h2>
<% comments_count = @post.comments.count %>
<%= image_tag @post.user.portrait_url, class: "portrait_s" %>
<%= link_to @post.user.name ,@post.user %> 发表于 <%= @post.created_at %>
  <span class="pull-right">
    <%= "阅览(#{@post.viewed_times})  评论(#{comments_count})" %>
  </span>
<hr />
<div class="content">
  <%= raw @post.content %>
</div>
<%= link_to('编辑', edit_post_path(@post)) if is_mine?(@post)  %> |
<%= link_to('删除', @post, method: 'delete', data: {confirm: "确定删除贴吗？"} ) if is_mine?(@post) || current_user.try(:is_admin?) %>
<% unless @post.file_records.blank? %>
  <div id="attachment" class="pull-right">
    <span>附件：</span>
    <% @post.file_records.each do |file| %>
      <%= link_to file.file_name, file.url %>
      <%= link_to('删除', file, method: 'delete' , data: { confirm: "确定删除附件吗？ \n #{file.file_name} " }) if is_mine?(@post) || current_user.try(:is_admin?) %>
      <br />
    <% end %>
  </div>
<% end%>
<hr />
<wb:share-button appkey="3ffQaP" addition="full" type="button" default_text="<%= @post.title %>（分享自好门的博客）" class="pull-right"></wb:share-button>
<div>
  <h3>评论列表</h3>
  <%= comments_count == 0 ? "还没有人评论。" : "共有#{comments_count}条评论"  %>
  <br />
  <% cmtcount = 0 + (@page.to_i - 1 ) * PostsController.per_page %>
  <% @comments.each do |comment| %>
    <div class="pull-left comment-portrait">
      <%= image_tag comment.user.portrait_url, class: "portrait_s" %>
    </div>
    <div class="comment-content pull-left">
      <%= cmtcount += 1 %>楼
      <%= link_to comment.user.name, comment.user %> &nbsp;&nbsp; 发表于：<%= comment.created_at %>
      <%= simple_format comment.content %>
      <a target="_self" onclick="repo('<%= cmtcount %>','<%= comment.user.name %>')" style="cursor:pointer;">回帖</a>
      <%= link_to '删除评论', comment, method: :delete, data: { confirm: '确定删除本条评论吗？' } if is_mine?(comment) || current_user.try(:is_admin?) %>
      <hr />
    </div>
  <% end %>
  <%= will_paginate( @comments, :prev_label=>'上一页',:next_label=>'下一页',:separator=>" | ") %>
</div>

<% if signed_in? %>
  <%= form_for(Comment.new) do |c| %>
    <%= c.hidden_field :user_id , value: current_user.id %>
    <%= c.hidden_field :post_id , value: @post.id %>
    <%= c.text_area :content , style: 'width:100%', onkeypress: 'ctrlEnter(event, "commit");' %>
    <%= c.submit '提交评论',   class: 'btn btn-primary', id: 'commit' %>
    <input type="button" onclick="clearRepoArea()" value="清空输入框" class="btn" />
  <% end %>
<% end %>
<% if notice.blank? %>
  <%= link_to_function "返回", "history.go(-1)" %>
<% else %>
  <%= link_to "返回", posts_path %>
<% end %>