config/routes.rb
BlogNagamemo::Application.routes.draw do
  resources :materials do
    member do
      get :now
    end
  end

  resources :histories do
    member do
      get :materials
    end
  end

  resources :offline_download_records do
    member do
      get :log
      get :status
      get :download
    end
  end

	resources :users do
		resources :comments
    resources :offline_download_records
		resources :posts do
			resources :comments
		end
	end

	resources :posts do
		resources :comments
	end

	resources :comments
  resources :file_records
	resources :sessions

	root 'posts#index'
	match 'about', to: 'static_page#about', via: 'get'
	match 'sign_up', to: 'users#new', via: 'get'
	match 'edit_me', to: 'users#edit_current_user', via: 'get'
	match 'show_me', to: 'users#show_current_user', via: 'get'
	match 'sign_in', to: 'sessions#new', via: 'get'
	match 'sign_out', to: 'sessions#destroy', via: 'delete'
	match 'quick_new_post' ,to:'posts#quick_new', via: 'post'
  match 'search', to: 'posts#search', via: 'get'
  match 'set_portrait', to:'users#set_portrait_img', via: 'post'
  match 'lunar_date', to: 'static_page#lunar_date', via: 'get'

end

app/models/material.rb
#encoding=utf-8
class Material < ActiveRecord::Base
  has_many :his_mats
  has_many :histories, through: :his_mats

  scope :niku, -> { where(["m_type = ?", "肉"]) }
  scope :yasai, -> { where(["m_type = ?", "菜"]) }
  scope :mada_nokotteru, -> { where(["materials.now > materials.cook_count"])}
  scope :nokottenai, -> {where(["materials.now <= materials.cook_count"])}

  def self.get_random_niku
    Material.mada_nokotteru.niku.find :first, order: "RAND()"
  end

  def self.get_random_yasai
    Material.mada_nokotteru.yasai.find :all, limit: 2, order: "RAND()"
  end

end

app/controllers/materials_controller.rb
#encoding=utf-8
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
    @nokottenai_materials = Material.nokottenai
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :m_type, :buy_unit, :buy_price, :cook_unit, :cook_count, :cook_price, :now)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% @material.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-borderd">
    <tr class="field">
      <td>食材名</td>
      <td><%= f.text_field :name, placeholder: "食材名" %></td>
    </tr>
    <tr class="field">
      <td>种类</td>
      <td><%= f.text_field :m_type , placeholder: "种类"%></td>
    </tr>
    <tr class="field">
      <td>购买单位</td>
      <td><%= f.text_field :buy_unit , placeholder: "购买单位"%></td>
    </tr>
    <tr class="field">
      <td>购买单价</td>
      <td><%= f.text_field :buy_price, placeholder: "购买单价"%></td>
    </tr>
    <tr class="field">
      <td>2顿单位</td>
      <td><%= f.text_field :cook_unit, placeholder: "2顿单位" %></td>
    </tr>
    <tr class="field">
      <td>2顿数量</td>
      <td><%= f.text_field :cook_count, placeholder: "2顿数量" %></td>
    </tr>
    <tr class="field">
      <td>2顿价格</td>
      <td><%= f.text_field :cook_price, placeholder: "2顿价格" %></td>
    </tr>
    <tr class="field">
      <td>剩余</td>
      <td><%= f.text_field :now, placeholder: "剩余" %></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit '提交', class: 'btn btn-primary', id: 'submit' %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>修改食材信息</h1>

<%= render 'form' %>

<%= link_to '查看', @material %> |
<%= link_to_function "返回", "history.go(-1)" %>

app/views/materials/index.html.erb
<h1>食材清单</h1>
<table class="table table-borderd">
  <thead>
    <tr>
      <th>食材</th>
      <th>种类</th>
      <th>购买单价</th>
      <th>2顿单价</th>
      <th>2顿消耗</th>
      <th>剩余</th>
      <th>可做</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.m_type %></td>
        <td><%= material.buy_price %>元/<%= material.buy_unit %></td>
        <td><%= material.cook_price %>元</td>
        <td><%= material.cook_count %><%= material.cook_unit %></td>
        <td><%= material.now %><%= material.cook_unit %></td>
        <td><%= (material.now / material.cook_count).to_i %>次</td>
        <td><%= link_to '详细', material %></td>
        <td><%= link_to '修改', edit_material_path(material) %></td>
        <td><%= link_to '删除', material, method: :delete, data: { confirm: '确认删除此食材?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '添加新食材', new_material_path %>

app/views/materials/new.html.erb
<h1>添加食材</h1>

<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "食材名" %>
  </div>
  <div class="field">
    <%= f.text_field :m_type , placeholder: "种类"%>
  </div>
  <div class="field">
    <%= f.text_field :buy_unit , placeholder: "购买单位"%>
  </div>
  <div class="field">
    <%= f.text_field :buy_price, placeholder: "购买单价"%>
  </div>
  <div class="field">
    <%= f.text_field :cook_unit, placeholder: "2顿单位" %>
  </div>
  <div class="field">
    <%= f.text_field :cook_count, placeholder: "2顿数量" %>
  </div>
  <div class="field">
    <%= f.text_field :cook_price, placeholder: "2顿价格" %>
  </div>
  <div class="field">
    <%= f.text_field :now, placeholder: "剩余" %>
  </div>
  <div class="actions">
		<%= f.submit '提交', class: 'btn btn-primary', id: 'submit' %>
  </div>
<% end %>

<%= link_to_function "返回", "history.go(-1)" %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-borderd">
  <tr>
    <th width="20%">食材名</th>
    <td>
      <%= @material.name %>
    </td>
  </tr>

  <tr>
    <th>类型</th>
    <td>
      <%= @material.m_type %>
    </td>
  </tr>


  <tr>
    <th>购买价格</th>
    <td>
      <%= @material.buy_price %>元/
      <%= @material.buy_unit %>
    </td>
  </tr>


  <tr>
    <th>2顿消耗</th>
    <td>
      <%= @material.cook_count %>
      <%= @material.cook_unit %>
    </td>
  </tr>

  <tr>
    <th>2顿花费</th>
    <td>
      <%= @material.cook_price %>元
    </td>
  </tr>

  <tr>
    <th>剩余</th>
    <td>
      <%= @material.now %>
      <%= @material.cook_unit %>
    </td>
  </tr>
</table>

<%= link_to '编辑', edit_material_path(@material) %> |
<% if notice.blank? %>
  <%= link_to_function "返回", "history.go(-1)" %>
<% else %>
  <%= link_to "返回", materials_path %>
<% end %>